### ISSUE TITLE
Error: Call to undefined method DB::require_field() 

### ISSUE THREAD

**Issue by Lukin-zz** [colymba/silverstripe-colorfield#2]
Getting an error when creating a new DB-Field with Type Color....?

Error: Call to undefined method DB::require_field() in /webspace/10/63664/bb-kosmetik.com/colorfield/code/Field/Color.php on line 57

**Comment by colymba** [comment]
Hi, it is a know issue. Basically I was using the master branch of the SS framework when making this module and `require_filed` has its syntax changed in 3.2 or master. (https://github.com/silverstripe/silverstripe-framework/blob/3.2/model/DB.php#L497)

Prior to that is was `requireField` which was the wrong syntax for static methods https://github.com/silverstripe/silverstripe-framework/blob/3.1/model/DB.php#L340

Upgrading to SS 3.2 will solve this. If that's not a possibility, you can edit the module.
